idf_component_register(
    SRCS
        "main.c"
        "gps_uart.c"
        "nmea_timing.c"
        "pps.c"
        "ethernet.c"
        "mdns_service.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        esp_driver_gpio
        esp_driver_spi
        esp_driver_uart
        esp_eth
        esp_event
        esp_netif
        esp_timer
        mdns
)
